### PR TITLE
Generate fonts using Fontship

### PR DESCRIPTION
**Pull request by alerque**
~~This is a follow-up to #1 and should be merged *after* it.~~

Fitting [Fontship](https://github.com/theleagueof/fontship) into a font development workflow using Runebender is something I'm experimenting with. This already works to generate TTF/OTF/WOFF fonts from the UFO sources found in the repository. Artifacts from every push will be available from the relevant checks, and when you tag the repository with an OpenFV compatible version (`vX.YYY`) it will also version the output fonts accordingly and attach them to a Github Release.

This tweaks the UFO name to include the style info. This is partly needed because Fontship doesn't work any other way yet, but it's also a good practice anyway I think because it will allow for future additional styles to be added without file namespace issues.

### CODE REVIEW

**Comment by alerque** [comment]
It looks like Github Actions won't run on this repository until either it's enabled in settings or there is a workflow file defined in the *master* branch or something like that. Normally it would show status info on this PR, but it isn't doing that yet.

You can see what the output is like from the [run on my fork](https://github.com/alerque/baby-shark/runs/814077638) including downloading the generated font artifacts. At the moment the fonts are generating but it looks like they are empty. I'll mark this PR as ready for review when it actually has the glyphs as they are in the UFO.

**Comment by alerque** [comment]
It appears the reason the TTF/OTF output is an empty font is that `fontmake` is falling down on the job, not `fontship`. Perhaps there is some key value missing from the UFO at this point, but `fontmake -u input -o ttf` produces and empty font.

**Comment by alerque** [comment]
I've rebased this on your master and tested it locally and the Fontship end of things is working fine, but the font is still empty. I tried directly with `fontmake` and got the same result.

You should be able to test this by enabling Actions on the repo, but you can also see it in action with fonts that work already such as [Libertinus](https://github.com/alerque/libertinus), [Raleway](https://github.com/theleagueof/raleway), and [League Spartan](https://github.com/theleagueof/league-spartan).

**Comment by eliheuer** [comment]
Thanks! I'm going to start working on this again soonish and I'll try to include the fontship stuff from this PR. But right now I need some time to look this over so I fully understand what is going on here.

**Comment by alerque** [comment]
Probably nothing is going on right now—this was a very early experiment with‌ Fontship and there have likely been several major version releases with breaking changes since. I'll give it a once over, update this PR, and make sure it's actually working before taking it out of draft mode if you're interested in merging it someday.

**Pull request closed without merging**
